-- Local/ephemeral Supabase only. SELECT-only contract checks.
-- Never run against Design Partner Cloud / production.

select
  to_regprocedure('public.list_source_health()') is not null as has_list_source_health,
  to_regprocedure('private.begin_source_ingestion_run(text,text)') is not null as has_begin_run,
  to_regprocedure('private.complete_source_ingestion_run(uuid,text,uuid,boolean,integer,integer,integer,text,text,jsonb)') is not null as has_complete_run,
  to_regprocedure('public.get_official_map_layer_geojson(text,double precision,double precision,double precision,double precision,double precision)') is not null as has_official_map_layer,
  to_regprocedure('public.get_official_covering_geojson_for_project(uuid)') is not null as has_official_covering,
  to_regprocedure('public.get_official_covering_summary_for_point(double precision,double precision)') is not null as has_official_covering_point,
  to_regprocedure('public.create_development_opportunity(uuid,text,text,text,text,text,double precision,double precision,numeric,numeric,numeric,text,uuid,text,text,text,text)') is not null as has_create_opportunity,
  to_regprocedure('public.execute_opportunity_screening_run(uuid)') is not null as has_execute_screening_run,
  to_regprocedure('public.segment_opportunity_run_into_sites(uuid)') is not null as has_segment_sites,
  to_regprocedure('private.land_cover_pref_score(text,jsonb)') is not null as has_land_cover_pref,
  to_regprocedure('public.apply_opportunity_run_assessments(uuid,jsonb)') is not null as has_apply_run_assessments,
  to_regprocedure('public.save_opportunity_from_run_candidate(uuid)') is not null as has_save_run_candidate,
  to_regprocedure('public.get_opportunity_run_geojson(uuid)') is not null as has_run_geojson,
  to_regclass('public.opportunity_run_zones') is not null as has_run_zones,
  to_regclass('public.official_physical_summaries') is not null as has_physical_summaries,
  to_regclass('public.official_transport_features') is not null as has_transport_features,
  to_regprocedure('public.refine_opportunity_run_candidates(uuid,uuid[])') is not null as has_refine_candidates,
  to_regclass('public.official_precision_summaries') is not null as has_precision_summaries,
  to_regclass('public.official_administrative_areas') is not null as has_admin_areas,
  to_regclass('public.opportunity_assessment_versions') is not null as has_assessment_versions,
  to_regclass('public.opportunity_reassessment_notices') is not null as has_reassessment_notices,
  to_regprocedure('public.promote_opportunity_to_project(uuid)') is not null as has_promote_opportunity,
  to_regprocedure('public.get_organization_official_spatial_matches(uuid)') is not null as has_official_spatial_matches,
  to_regprocedure('private.apply_observation_snapshot_changes(uuid, uuid, boolean, text, text)') is not null as has_apply_changes,
  exists (select 1 from pg_extension where extname = 'postgis') as has_postgis,
  exists (select 1 from storage.buckets where id = 'project-documents') as has_project_documents_bucket;
